# app/auto_fix.py
import os
import logging
from github import Github, GithubException
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage  

logger = logging.getLogger(__name__)


llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.1,
    groq_api_key=os.getenv("GROQ_API_KEY")
)

def generate_fixed_code(original_code: str, issues: list[dict], filename: str) -> str:
    """Ask Groq to fix all detected issues in a file."""

    issues_summary = "\n".join([
        f"- Line {i.get('line', '?')} [{i.get('severity')}] {i.get('issue')} → Fix: {i.get('fix_suggestion')}"
        for i in issues
    ])

    system_prompt = """You are an expert code security engineer.
You will receive a file with known security issues and a list of those issues with suggested fixes.
Return ONLY the fully corrected file contents — no explanations, no markdown, no code fences.
Preserve all original formatting, indentation, and logic. Only fix the listed issues."""

    user_prompt = f"""File: {filename}

Known issues to fix:
{issues_summary}

Original code:
{original_code}

Return the fully corrected file contents only:"""

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ])

    return response.content.strip()


def create_fix_pr(
    installation_token: str,
    repo_full_name: str,
    pr_number: int,
    pr_head_sha: str,
    pr_head_branch: str,
    issues_by_file: dict[str, list[dict]],
    file_contents: dict[str, str]
) -> dict:
    """
    Creates a new branch with fixes applied and opens a pull request.
    Returns info about the created PR.
    """
    g = Github(installation_token)
    repo = g.get_repo(repo_full_name)

    fix_branch = f"codesentinel/fix-pr-{pr_number}"

    # Create fix branch from the PR's head commit
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{fix_branch}",
            sha=pr_head_sha
        )
        logger.info(f"✅ Created branch {fix_branch}")
    except GithubException as e:
        if e.status == 422:
            logger.warning(f"Branch {fix_branch} already exists, continuing...")
        else:
            raise

    fixed_files = []
    fix_descriptions = []

    for filename, issues in issues_by_file.items():
        original_code = file_contents.get(filename)
        if not original_code:
            logger.warning(f"⚠️ No content for {filename}, skipping")
            continue

        logger.info(f"🔧 Generating fix for {filename} ({len(issues)} issues)")
        fixed_code = generate_fixed_code(original_code, issues, filename)

        # Get current file SHA (needed for update)
        try:
            file_obj = repo.get_contents(filename, ref=fix_branch)
            file_sha = file_obj.sha
        except GithubException:
            logger.warning(f"Could not get SHA for {filename}, skipping")
            continue

        # Commit the fix
        repo.update_file(
            path=filename,
            message=f"fix: auto-fix security issues in {filename} [CodeSentinel]",
            content=fixed_code,
            sha=file_sha,
            branch=fix_branch
        )
        fixed_files.append(filename)

        for issue in issues:
            fix_descriptions.append(
                f"- **{filename}** line {issue.get('line', '?')} "
                f"[{issue.get('severity')}]: {issue.get('issue')}"
            )

    if not fixed_files:
        return {"status": "no_fixes", "message": "No fixable files found"}

    # Build PR body
    pr_body = f"""## 🤖 CodeSentinel Auto-Fix

This PR was automatically generated to fix issues found in PR #{pr_number}.

### Issues Fixed
{chr(10).join(fix_descriptions)}

### ⚠️ Important
- Review these changes before merging
- Auto-fixes are AI-generated — verify correctness
- Original PR: #{pr_number}

---
*Generated by [CodeSentinel](https://github.com) AI Code Review*"""

    # Open the fix PR
    created_pr = repo.create_pull(
        title=f"🤖 [CodeSentinel] Auto-fix for PR #{pr_number}",
        body=pr_body,
        head=fix_branch,
        base=pr_head_branch
    )

    logger.info(f"✅ Fix PR created: {created_pr.html_url}")

    return {
        "status": "created",
        "fix_pr_number": created_pr.number,
        "fix_pr_url": created_pr.html_url,
        "fixed_files": fixed_files,
        "branch": fix_branch
    }